Repository MPAS-Dev/geometric_features, pull requests merged in 2024-12, with the labels that each got.

#216 Add CI workflow to automatically update pre-commit and its dependencies
  .github/workflows/build_workflow.yml
  .github/workflows/pre_commit_update_workflow.yml
Labels: ci

#218 Fix sea-ice historical median features
  geometric_data/seaice/region/April_Historical_Median_Sea_Ice_Extent/region.geojson
  geometric_data/seaice/region/August_Historical_Median_Sea_Ice_Extent/region.geojson
  geometric_data/seaice/region/December_Historical_Median_Sea_Ice_Extent/region.geojson
  geometric_data/seaice/region/February_Historical_Median_Sea_Ice_Extent/region.geojson
  geometric_data/seaice/region/January_Historical_Median_Sea_Ice_Extent/region.geojson
  geometric_data/seaice/region/July_Historical_Median_Sea_Ice_Extent/region.geojson
  geometric_data/seaice/region/June_Historical_Median_Sea_Ice_Extent/region.geojson
  geometric_data/seaice/region/March_Historical_Median_Sea_Ice_Extent/region.geojson
  geometric_data/seaice/region/May_Historical_Median_Sea_Ice_Extent/region.geojson
  geometric_data/seaice/region/November_Historical_Median_Sea_Ice_Extent/region.geojson
  geometric_data/seaice/region/October_Historical_Median_Sea_Ice_Extent/region.geojson
  geometric_data/seaice/region/September_Historical_Median_Sea_Ice_Extent/region.geojson
Labels: bug

#219 Fix ocean extended features
  geometric_data/landice/region/northWestGreenland2_oceanExtended/region.geojson
  geometric_data/landice/region/westCentralGreenland1_oceanExtended/region.geojson
Labels: bug

#220 Add test to make sure `features_and_tags.json` looks as expected
  geometric_features/features_and_tags.json
  geometric_features/test/test_features_and_tags.py
  geometric_features/utils.py
Labels: enhancement

#221 Add `pre-commit` for code linting
  .flake8
  .github/workflows/build_workflow.yml
  .github/workflows/docs_workflow.yml
  .pre-commit-config.yaml
  LICENSE
  contributors/CONTRIBUTORS_HEADER
  contributors/list_contributors.py
  dev-spec.txt
  examples/README.md
  examples/setup_antarctic_basins.py
  examples/setup_extended_antarctic_basins.py
  examples/setup_ice_shelves.py
  examples/setup_ocean_critical_passages.py
  examples/setup_ocean_land_coverage.py
  examples/setup_ocean_region_groups.py
  examples/setup_ocean_standard_transport_sections.py
  feature_creation_scripts/antarctic_ocean_regions/antarctic_ocean_regions.py
  feature_creation_scripts/arctic_ocean_regions/arctic_ocean_regions_partI.py
  feature_creation_scripts/arctic_ocean_regions/arctic_ocean_regions_partII.py
  feature_creation_scripts/extract_bedmachine_coastlines/extract_bedmachine_coastlines.py
  feature_creation_scripts/extract_bedmap2_ice_coverage/bedamp2_to_netcdf.py
  feature_creation_scripts/extract_bedmap2_ice_coverage/extract_bedmap2_ice_coverage.py
  feature_creation_scripts/iceshelves/README.md
  feature_creation_scripts/iceshelves/bedmap2_to_netcdf.py
  feature_creation_scripts/iceshelves/ice_vel_to_bedmap2.py
  feature_creation_scripts/iceshelves/plot_streamline.py
  feature_creation_scripts/iceshelves/polar.py
  feature_creation_scripts/iceshelves/write_basin_distances.py
  feature_creation_scripts/iceshelves/write_basin_images.py
  feature_creation_scripts/iceshelves/write_basin_numbers.py
  feature_creation_scripts/iceshelves/write_expanded_overlaps.py
  feature_creation_scripts/iceshelves/write_iceshelf_distance.py
  feature_creation_scripts/iceshelves/write_iceshelf_features.py
  feature_creation_scripts/iceshelves/write_iceshelf_numbers.py
  feature_creation_scripts/ismip6_antarctic_ocean_regions/README.md
  feature_creation_scripts/ismip6_antarctic_ocean_regions/ismip6_antarctic_ocean_regions.py
  feature_creation_scripts/ismip6_landice_basins/basin_masks_to_geojson_regions.py
  feature_creation_scripts/transport_transects/OSNAPsections.py
  feature_creation_scripts/transport_transects/flipOSNAP_renameArcticTransectsTag.py
  feature_creation_scripts/transport_transects/transport_sections.m
  geometric_features/__main__.py
  geometric_features/aggregation/__init__.py
  geometric_features/aggregation/landice/__init__.py
  geometric_features/aggregation/ocean/__init__.py
  geometric_features/aggregation/ocean/ice_shelf_regions.py
  geometric_features/aggregation/ocean/moc_basins.py
  geometric_features/aggregation/ocean/ocean_basins.py
  geometric_features/download.py
  geometric_features/feature_collection.py
  geometric_features/geometric_features.py
  geometric_features/plot.py
  geometric_features/test/__init__.py
  geometric_features/test/test_aggregation.py
  geometric_features/test/test_feature_collection.py
  geometric_features/test/test_geometric_features.py
  geometric_features/utils.py
  setup.py
Labels: clean up, ci

#223 Fix `flake8` lint in `geometric_features`
  .github/workflows/build_workflow.yml
  geometric_features/aggregation/__init__.py
  geometric_features/aggregation/landice/nasa_greenland_extended.py
  geometric_features/aggregation/seaice/historical_sea_ice.py
  geometric_features/feature_collection.py
  geometric_features/plot.py
  geometric_features/test/test_aggregation.py
  geometric_features/test/test_feature_collection.py
  geometric_features/test/test_features_and_tags.py
  geometric_features/test/test_geometric_features.py
  geometric_features/utils.py
Labels: clean up

#225 Fix test_features_and_tags
  dev-spec.txt
  geometric_features/test/test_features_and_tags.py
  recipe/meta.yaml
Labels: bug
